[metadata]
project_test = true

[versions]
android-gradle-plugin = "8.13.0"
kotlin = "2.2.20"
ksp = "2.2.20-2.0.3"
androidx-compose-bom = "2025.10.01"
androidx-core = "1.17.0"
androidx-junit = "1.3.0"
androidx-espresso-core = "3.7.0"
androidx-lifecycle = "2.9.4"
androidx-appcompat = "1.7.1"
androidx-material3 = "1.5.0-alpha07"
androidx-annotation = "1.9.1"
androidx-constraintlayout = "2.2.1"
androidx-uiautomator = "2.3.0"
androidx-benchmark-macr-junit4 = "1.4.1"
androidx-baselineprofile = "1.4.1"
androidx-profileinstaller = "1.4.1"
androidx-room = "2.8.3"
androidx-navigation = "2.9.5"
androidx-camerax = "1.5.1"
androidx-media3 = "1.8.0"
androidx-slice = "1.1.0-alpha02"
androidx-slice-builder-ktx = "1.0.0-alpha08"
androidx-recyclerview = "1.4.0"
androidx-activity = "1.11.0"
androidx-worker = "2.11.0"
androidx-splash-screen = "1.2.0-rc01"
junit = "4.13.2"

google-android-libraries-maps-platform-secrets-gradle-plugin = "2.0.1"
google-generativeai = "0.9.0"
google-material = "1.13.0"
google-web-rtc = "1.0.32006"
google-gson = "2.13.2"
google-barcode-scanning = "17.3.0"
google-zxing = "3.5.3"

hilt-plugin = "2.55"
hilt = "2.57.2"
hilt-lifecycle-viewmodel = "1.3.0"

okhttp = "5.3.0"
retrofit = "3.0.0"
moshi = "1.15.2"
retrofit2-kotlin-coroutines-adapter = "0.9.2"
coil = "3.3.0"
haze = "1.6.10"
image-compressor = "3.0.1"
tencent-cos-lite = "5.9.47"
jetty-server = "12.1.3"
rabbitmq = "5.27.0"
netty-all = "4.1.112.Final"
jmdns = "3.6.2"
tinder-scarlet = "0.1.12"
telephoto-zoomable = "0.18.0"
compose-card-stack = "1.0.1"
ffmpeg-kit-full = "6.0-2.LTS"

appsets-gradle-plugin = "1.0"

[libraries]
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidx-uiautomator" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-splash-screen" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }

androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }

androidx-slice-core = { group = "androidx.slice", name = "slice-core", version.ref = "androidx-slice" }
androidx-slice-builders = { group = "androidx.slice", name = "slice-builders", version.ref = "androidx-slice" }
androidx-slice-builders-ktx = { group = "androidx.slice", name = "slice-builders-ktx", version.ref = "androidx-slice-builder-ktx" }

androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }

androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidx-benchmark-macr-junit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidx-profileinstaller" }

androidx-room = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }

androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "androidx-media3" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "androidx-media3" }
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "androidx-media3" }

androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "androidx-camerax" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "androidx-camerax" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "androidx-camerax" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "androidx-camerax" }
androidx-camera-mlkit-vision = { group = "androidx.camera", name = "camera-mlkit-vision", version.ref = "androidx-camerax" }

androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-worker" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-kotlin-coroutines-adapter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlin-coroutines-adapter", version.ref = "retrofit2-kotlin-coroutines-adapter" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

coil = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-gif = { group = "io.coil-kt.coil3", name = "coil-gif", version.ref = "coil" }
coil-video = { group = "io.coil-kt.coil3", name = "coil-video", version.ref = "coil" }

telephoto-zoomable = { group = "me.saket.telephoto", name = "zoomable", version.ref = "telephoto-zoomable" }
telephoto-zoomable-peek-overlay = { group = "me.saket.telephoto", name = "zoomable-peek-overlay", version.ref = "telephoto-zoomable" }

google-material = { group = "com.google.android.material", name = "material", version.ref = "google-material" }
google-generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "google-generativeai" }
google-barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "google-barcode-scanning" }
google-zxing = { group = "com.google.zxing", name = "core", version.ref = "google-zxing" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "google-gson" }
google-webrtc = { group = "org.webrtc", name = "google-webrtc", version.ref = "google-web-rtc" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-complier = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-lifecycle-viewmodel = { group = "androidx.hilt", name = "hilt-lifecycle-viewmodel", version.ref = "hilt-lifecycle-viewmodel" }

haze = { group = "dev.chrisbanes.haze", name = "haze", version.ref = "haze" }
haze-materials = { group = "dev.chrisbanes.haze", name = "haze-materials", version.ref = "haze" }
image-compressor = { group = "id.zelory", name = "compressor", version.ref = "image-compressor" }
tencent-cos-lite = { group = "com.qcloud.cos", name = "cos-android-lite-nobeacon", version.ref = "tencent-cos-lite" }
rabbit-amqp = { group = "com.rabbitmq", name = "amqp-client", version.ref = "rabbitmq" }
jetty-server = { group = "org.eclipse.jetty", name = "jetty-server", version.ref = "jetty-server" }
netty-all = { group = "io.netty", name = "netty-all", version.ref = "netty-all" }
tinder-scarlet = { group = "com.tinder.scarlet", name = "scarlet", version.ref = "tinder-scarlet" }
jmdns = { group = "org.jmdns", name = "jmdns", version.ref = "jmdns" }
compose-card-stack = { module = "com.github.msusman1:compose-card-stack", version.ref = "compose-card-stack" }
ffmpeg-kit-full = { module = "com.arthenica:ffmpeg-kit-full", version.ref = "ffmpeg-kit-full" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
android-test = { id = "com.android.test", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-android-libraries-mapsplatform-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "google-android-libraries-maps-platform-secrets-gradle-plugin" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-baselineprofile" }

hilt = { id = "hilt-android-gradle-plugin", version.ref = "hilt-plugin" }

appsets-plugin = { id = "xcj.app.plugin.gradle", version.ref = "appsets-gradle-plugin" }

